### ISSUE TITLE
Potential typo in notes

### ISSUE THREAD

**Issue by jmccormac01** [saigrain/republic#1]
Hi Suzanne, 
I've been reading through the notes on Republic (and frantically swotting up on matricies). I think there might be a small typo in the final line of the shorter notation section. Should ```the nth element of E_j is the dot product of F_jk``` be ```r_j``` instead of ```E_j```? 

I have some questions on the matrix blocking but I should hopefully be able to understand that more by looking at the code. 

I have been working on code for simulating and injecting trends then generating the CBVs. It's still fairly basic atm but I am planning to make it more PLATO-like over the next while. It would be great to use Republic on those simulated light curves and my CBVs to see how good the correction is. 

Cheers,
James

**Comment by saigrain** [comment]
Thanks for pointing that out James - you were right - I fixed it
